#!/bin/bash

# Installation script for Numix icon themes, written and maintained by
# Joshua Fogg (joshua.h.fogg@gmail.com). A merge of the original python
# version and a fork of the Faenza installer written by Tiheum
# (matthieu.james@gmail.com)

ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "Icon themes will be installed in $HOME/.icons making them available to only you."
	echo "To make them available for all users, run this script as root."
	echo "Hardcoded cannot be fixed either as to make the required changes needs root."
else
	echo "Icon themes will be installed in /usr/share/icons and are available for all users."
	echo "Because you're running as root you will also be able to fix hardcoded icons."
fi
read -p "Do you want to continue ? [Y]es, [N]o : " response
case $response in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Wrong value: installaton aborted."; exit 1;;
esac

DIR="$( cd -P "$( dirname "$0" )" && pwd )"
cd $DIR

tar xf Numix.tar.gz 2>/dev/null
tar xf Numix-Circle.tar.gz 2>/dev/null
tar xf Numix-Mono.tar.gz 2>/dev/null
tar xf Numix-Shine.tar.gz 2>/dev/null
tar xf Numix-uTouch-GS.tar.gz 2>/dev/null
tar xf Numix-uTouch.tar.gz 2>/dev/null


if [ -d $HOME/.icons/Faenza ]
then
	echo
	read -p "An existing installation have been detected in $HOME/.icons. Remove it previously ? [Y]es, [N]o :" response
	case $response in
		[Yy]* ) rm -Rf $HOME/.icons/Numix 2>/dev/null; rm -Rf $HOME/.icons/Numix-Circle 2>/dev/null; rm -Rf $HOME/.icons/Numix-Mono. 2>/dev/null; rm -Rf $HOME/.icons/Numix-Shine 2>/dev/null; rm -Rf $HOME/.icons/Numix-uTouch-GS 2>/dev/null; rm -Rf $HOME/.icons/Numix-uTouch 2>/dev/null;;
	    * ) ;;
	esac
fi

if [ "$UID" -eq "$ROOT_UID" ]
then
	if [ -d /usr/share/icons/Numix ]
	then
		echo
		read -p "An existing installation has been detected in /usr/share/icons. Remove it previously ? [Y]es, [N]o :" response
		case $response in
			[Yy]* ) rm -Rf /usr/share/icons/Numix 2>/dev/null; rm -Rf /usr/share/icons/Numix-Circle 2>/dev/null; rm -Rf /usr/share/icons/Numix-Mono 2>/dev/null; rm -Rf /usr/share/icons/Numix-Shine 2>/dev/null; rm -Rf /usr/share/icons/Numix-uTouch-GS 2>/dev/null; rm -Rf /usr/share/icons/Numix-uTouch 2>/dev/null;;
		    * ) ;;
		esac
		echo
	fi
	cp -R ./Numix/ /usr/share/icons/
	cp -R ./Numix-Circle/ /usr/share/icons/
	cp -R ./Numix-Mono/ /usr/share/icons/
	cp -R ./Numix-Shine/ /usr/share/icons/
	cp -R ./Numix-uTouch-GS/ /usr/share/icons/
	cp -R ./Numix-uTouch/ /usr/share/icons/
	install_dir=/usr/share/icons/
else
	cp -R ./Numix/ $HOME/.icons/
	cp -R ./Numix-Circle/ $HOME/.icons/
	cp -R ./Numix-Mono/ $HOME/.icons/
	cp -R ./Numix-Shine/ $HOME/.icons/
	cp -R ./Numix-uTouch-GS/ $HOME/.icons/
	cp -R ./Numix-uTouch/ $HOME/.icons/
	install_dir=$HOME/.icons/
fi

echo
echo "Installation complete."

echo "The script will now attempt to fix hardcoded icons."
echo "The changes made are not automatically reversable."
read -p "Do you want to continue ? [Y]es, [n]o : " response
case $response in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Enjoy!"; exit 1;;
esac

python3 hc-fix.py

echo "Hardcoded icons fixed. Enjoy !"
exit 0
