#!/bin/bash

# Uninstallation script for Numix icon themes, written and maintained by
# Joshua Fogg (joshua.h.fogg@gmail.com). A merge of the original python
# version and a fork of the Faenza installer written by Tiheum
# (matthieu.james@gmail.com)

ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "Numix icon themes installed in $HOME/.icons will be removed."
else
	echo "Numix icon themes installed in /usr/share/icons will be removed."
fi
read -p "Do you want to continue ? [Y]es, [N]o : " response
case $response in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Wrong value: uninstall aborted."; exit 1;;
esac

if [ "$UID" -eq "$ROOT_UID" ]
then
	rm -Rf /usr/share/icons/Numix 2>/dev/null
	rm -Rf /usr/share/icons/Numix-Circle 2>/dev/null
	rm -Rf /usr/share/icons/Numic-Mono 2>/dev/null
	rm -Rf /usr/share/icons/Numix-Shine 2>/dev/null
	rm -Rf /usr/share/icons/Numix-uTouch-GS 2>/dev/null
	rm -Rf /usr/share/icons/Numix-uTouch 2>/dev/null
else
	rm -Rf $HOME/.icons/Numix 2>/dev/null
	rm -Rf $HOME/.icons/Numix-Circle 2>/dev/null
	rm -Rf $HOME/.icons/Numic-Mono 2>/dev/null
	rm -Rf $HOME/.icons/Numix-Shine 2>/dev/null
	rm -Rf $HOME/.icons/Numix-uTouch-GS 2>/dev/null
	rm -Rf $HOME/.icons/Numix-uTouch 2>/dev/null
fi

echo "Uninstall complete."

echo "The script will now attempt to unfix hardcoded icons."
read -p "Did you fix them during installation? [Y]es, [n]o : " response
case $response in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Enjoy!"; exit 1;;
esac

python3 hc-unfix.py

exit 0
