#!/bin/sh

# Put all these scripts (you don't have to include the README!) into the
# "scalable" folder of Numix-Technic and run this script. It'll generate app
# icons for the apps and non-app icons for the non-apps without you having to
# manually specify what to do for each folder.

cd ./actions
../autotouch-all -nonapp "."
# No need for animations; there are only two
cd ../apps
../autotouch-all "" "."
cd ../categories
../autotouch-all -nonapp "."
cd ../devices
../autotouch-all -nonapp "."
cd ../emblems
../autotouch-all -nonapp "."
cd ../mimetypes
../autotouch-all -nonapp "."
cd ../places
../autotouch-all -nonapp "."
cd ../status
../autotouch-all -nonapp "."
cd ../
rm */old
echo "Finished!"
