#!/bin/sh
if [[ `which svgcleaner-cli` ]]; then
    find . -type f -name '*.svg' -print0 | while IFS= read -r -d '' FILE; do
        echo "Optimizing $FILE"
        svgcleaner-cli "$FILE" "$FILE" --colors-to-rrggbb --convert-to-relative --compact-output --create-viewbox --merge-gradients --remove-ai-atts --remove-ai-elts --remove-corel-atts --remove-corel-elts --remove-default-atts --remove-duplicated-defs --remove-empty-containers --remove-fill-props --remove-inkscape-atts --remove-inkscape-elts --remove-invisible-elts --remove-metadata-elts --remove-msvisio-atts --remove-msvisio-elts --remove-nonsvg-elts --remove-notappl-atts --remove-outside-elts --remove-proc-instr --remove-prolog --remove-sketch-atts --remove-sketch-elts --remove-sodipodi-atts --remove-sodipodi-elts --remove-stroke-props --remove-unreferenced-ids --remove-unused-defs --remove-unused-xlinks --remove-version --rrggbb-to-rgb --trim-ids --ungroup-containers
        echo "uTouchifying $FILE"
        cat "$FILE" | ./autotouch.js > "$FILE.new"
        mv "$FILE" "$FILE.old"
        mv "$FILE.new" "$FILE"
        echo "Optimizing $FILE"
        svgcleaner-cli "$FILE" "$FILE" --colors-to-rrggbb --convert-to-relative --compact-output --create-viewbox --merge-gradients --remove-ai-atts --remove-ai-elts --remove-corel-atts --remove-corel-elts --remove-default-atts --remove-duplicated-defs --remove-empty-containers --remove-fill-props --remove-inkscape-atts --remove-inkscape-elts --remove-invisible-elts --remove-metadata-elts --remove-msvisio-atts --remove-msvisio-elts --remove-nonsvg-elts --remove-notappl-atts --remove-outside-elts --remove-proc-instr --remove-prolog --remove-sketch-atts --remove-sketch-elts --remove-sodipodi-atts --remove-sodipodi-elts --remove-stroke-props --remove-unreferenced-ids --remove-unused-defs --remove-unused-xlinks --remove-version --rrggbb-to-rgb --trim-ids --ungroup-containers
    done
    echo "Moving backup files into folder \"old\""
    mkdir -p old
    find . -type f -name '*.old' -print0 | while IFS= read -r -d '' OLD; do
        mv "$OLD" old
    done
else
    echo "svgcleaner-cli is not installed."
    exit 1
fi
